language: python
python:
  - "3.9"
#  - "3.7"
install: "pip install -r requirements.txt"
script: py.test --cov --cov-report=xml owm tests -vv
after_success:
  - coveralls
  - sonar-scanner
addons:
  sonarcloud:
    organization: jwoytek
      #  script:
      #    - sonar-scanner
