language: python
python:
  - "3.9"
#  - "3.7"
install: "pip install -r requirements.txt"
script: py.test --cov owm tests -vv
after_success:
  - coveralls
addons:
  sonarcloud:
    organization: jwoytek
  script:
    - sonar-scanner
